nome = input('Digite seu nome completo: ')
print('Seu nome completo apenas com letras MAIÚSCULAS fica: {}'.format(nome.upper()))
print('Seu nome completo apenas com letras MINÚSCULAS fica: {}'.format(nome.lower()))
div = nome.split()
nome = '-'.join(div)
nome = nome.replace('-', '')
print('Seu nome completo possui {} letras'.format(len(nome)))
pn = len(div[0])
print('Seu primeiro nome possui {} letras'.format(pn))
